/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_MathLib */

#ifndef _Included_org_example_MathLib
#define _Included_org_example_MathLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_MathLib
 * Method:    plus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_example_MathLib_plus
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_example_MathLib
 * Method:    minus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_example_MathLib_minus
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_example_MathLib
 * Method:    div
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_org_example_MathLib_div
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_example_MathLib
 * Method:    multi
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_example_MathLib_multi
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
